//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeuristicAlgorithms.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeuristicAlgorithms.Utilities.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of arguments are not set..
        /// </summary>
        internal static string AmountOfArgumentsNotSetMessage {
            get {
                return ResourceManager.GetString("AmountOfArgumentsNotSetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begining temperature must be higher than ending temperature..
        /// </summary>
        internal static string BeginingLowerThanEndingTemperature {
            get {
                return ResourceManager.GetString("BeginingLowerThanEndingTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string CircleFunctionArguments {
            get {
                return ResourceManager.GetString("CircleFunctionArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string Fireflies {
            get {
                return ResourceManager.GetString("Fireflies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one iteration..
        /// </summary>
        internal static string TooFewIterations {
            get {
                return ResourceManager.GetString("TooFewIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooling must be lower than one..
        /// </summary>
        internal static string TooHighCooling {
            get {
                return ResourceManager.GetString("TooHighCooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooling must be higher than zero..
        /// </summary>
        internal static string TooLowCooling {
            get {
                return ResourceManager.GetString("TooLowCooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature is too low..
        /// </summary>
        internal static string TooLowTemperature {
            get {
                return ResourceManager.GetString("TooLowTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterations must be less, than one milion..
        /// </summary>
        internal static string TooMuchIterations {
            get {
                return ResourceManager.GetString("TooMuchIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number is not in domain..
        /// </summary>
        internal static string ValueOutOfDomainMessage {
            get {
                return ResourceManager.GetString("ValueOutOfDomainMessage", resourceCulture);
            }
        }
    }
}
